{
  "textureFormat": "png",
  "scale": 1,
  "scaleMethod": "BILINEAR",
  "width": 1024,
  "height": 1024,
  "powerOfTwo": false,
  "padding": 0,
  "extrude": 0,
  "allowRotation": true,
  "allowTrim": true,
  "trimMode": "trim",
  "alphaThreshold": 0,
  "detectIdentical": true,
  "include": "",
  "exclude": "",
  "recursive": false,
  "packer": "MaxRectsPacker",
  "packerMethod": "Smart"
}